package io.github.glavin.votingsystem.core.ui

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006E2C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5DCB72)
val onPrimaryContainerLight = Color(0xFF00531F)
val secondaryLight = Color(0xFF406744)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBEEBBE)
val onSecondaryContainerLight = Color(0xFF446C47)
val tertiaryLight = Color(0xFF00658B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3CC1FF)
val onTertiaryContainerLight = Color(0xFF004C6A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF0)
val onBackgroundLight = Color(0xFF171D17)
val surfaceLight = Color(0xFFF5FBF0)
val onSurfaceLight = Color(0xFF171D17)
val surfaceVariantLight = Color(0xFFD9E6D6)
val onSurfaceVariantLight = Color(0xFF3E4A3E)
val outlineLight = Color(0xFF6E7A6D)
val outlineVariantLight = Color(0xFFBDCABA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322B)
val inverseOnSurfaceLight = Color(0xFFECF3E8)
val inversePrimaryLight = Color(0xFF6FDD82)
val surfaceDimLight = Color(0xFFD6DCD1)
val surfaceBrightLight = Color(0xFFF5FBF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF6EB)
val surfaceContainerLight = Color(0xFFE9F0E5)
val surfaceContainerHighLight = Color(0xFFE4EADF)
val surfaceContainerHighestLight = Color(0xFFDEE4DA)

val primaryLightMediumContrast = Color(0xFF004016)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF007E34)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF173E1E)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4E7651)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003B52)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF0075A0)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5FBF0)
val onBackgroundLightMediumContrast = Color(0xFF171D17)
val surfaceLightMediumContrast = Color(0xFFF5FBF0)
val onSurfaceLightMediumContrast = Color(0xFF0D130D)
val surfaceVariantLightMediumContrast = Color(0xFFD9E6D6)
val onSurfaceVariantLightMediumContrast = Color(0xFF2E392E)
val outlineLightMediumContrast = Color(0xFF4A5549)
val outlineVariantLightMediumContrast = Color(0xFF647063)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C322B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF3E8)
val inversePrimaryLightMediumContrast = Color(0xFF6FDD82)
val surfaceDimLightMediumContrast = Color(0xFFC2C8BE)
val surfaceBrightLightMediumContrast = Color(0xFFF5FBF0)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF6EB)
val surfaceContainerLightMediumContrast = Color(0xFFE4EADF)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DFD4)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD4C9)

val primaryLightHighContrast = Color(0xFF003411)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005520)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0B3315)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2A5130)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF003044)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF004F6D)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FBF0)
val onBackgroundLightHighContrast = Color(0xFF171D17)
val surfaceLightHighContrast = Color(0xFFF5FBF0)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD9E6D6)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF242F24)
val outlineVariantLightHighContrast = Color(0xFF414C40)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C322B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF6FDD82)
val surfaceDimLightHighContrast = Color(0xFFB4BBB1)
val surfaceBrightLightHighContrast = Color(0xFFF5FBF0)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF3E8)
val surfaceContainerLightHighContrast = Color(0xFFDEE4DA)
val surfaceContainerHighLightHighContrast = Color(0xFFD0D6CC)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C8BE)

val primaryDark = Color(0xFF79E88B)
val onPrimaryDark = Color(0xFF003913)
val primaryContainerDark = Color(0xFF5DCB72)
val onPrimaryContainerDark = Color(0xFF00531F)
val secondaryDark = Color(0xFFA5D2A6)
val onSecondaryDark = Color(0xFF103819)
val secondaryContainerDark = Color(0xFF2A5130)
val onSecondaryContainerDark = Color(0xFF98C398)
val tertiaryDark = Color(0xFF9BD9FF)
val onTertiaryDark = Color(0xFF00344A)
val tertiaryContainerDark = Color(0xFF3CC1FF)
val onTertiaryContainerDark = Color(0xFF004C6A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F150F)
val onBackgroundDark = Color(0xFFDEE4DA)
val surfaceDark = Color(0xFF0F150F)
val onSurfaceDark = Color(0xFFDEE4DA)
val surfaceVariantDark = Color(0xFF3E4A3E)
val onSurfaceVariantDark = Color(0xFFBDCABA)
val outlineDark = Color(0xFF889486)
val outlineVariantDark = Color(0xFF3E4A3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DA)
val inverseOnSurfaceDark = Color(0xFF2C322B)
val inversePrimaryDark = Color(0xFF006E2C)
val surfaceDimDark = Color(0xFF0F150F)
val surfaceBrightDark = Color(0xFF343B34)
val surfaceContainerLowestDark = Color(0xFF0A100A)
val surfaceContainerLowDark = Color(0xFF171D17)
val surfaceContainerDark = Color(0xFF1B211B)
val surfaceContainerHighDark = Color(0xFF252C25)
val surfaceContainerHighestDark = Color(0xFF30362F)

val primaryDarkMediumContrast = Color(0xFF85F496)
val onPrimaryDarkMediumContrast = Color(0xFF002D0D)
val primaryContainerDarkMediumContrast = Color(0xFF5DCB72)
val onPrimaryContainerDarkMediumContrast = Color(0xFF00310F)
val secondaryDarkMediumContrast = Color(0xFFBBE8BB)
val onSecondaryDarkMediumContrast = Color(0xFF032D0F)
val secondaryContainerDarkMediumContrast = Color(0xFF719B73)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB7E2FF)
val onTertiaryDarkMediumContrast = Color(0xFF00293B)
val tertiaryContainerDarkMediumContrast = Color(0xFF3CC1FF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF002D40)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F150F)
val onBackgroundDarkMediumContrast = Color(0xFFDEE4DA)
val surfaceDarkMediumContrast = Color(0xFF0F150F)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3E4A3E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD3E0D0)
val outlineDarkMediumContrast = Color(0xFFA9B5A6)
val outlineVariantDarkMediumContrast = Color(0xFF879485)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE4DA)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252C25)
val inversePrimaryDarkMediumContrast = Color(0xFF005420)
val surfaceDimDarkMediumContrast = Color(0xFF0F150F)
val surfaceBrightDarkMediumContrast = Color(0xFF40463F)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040904)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F19)
val surfaceContainerDarkMediumContrast = Color(0xFF232923)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E342D)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F38)

val primaryDarkHighContrast = Color(0xFFC2FFC4)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF6BD97E)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F02)
val secondaryDarkHighContrast = Color(0xFFCEFCCD)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA2CEA2)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F02)
val tertiaryDarkHighContrast = Color(0xFFE2F2FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF72CCFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000D16)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F150F)
val onBackgroundDarkHighContrast = Color(0xFFDEE4DA)
val surfaceDarkHighContrast = Color(0xFF0F150F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3E4A3E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE7F4E3)
val outlineVariantDarkHighContrast = Color(0xFFBAC6B6)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE4DA)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005420)
val surfaceDimDarkHighContrast = Color(0xFF0F150F)
val surfaceBrightDarkHighContrast = Color(0xFF4B524A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B211B)
val surfaceContainerDarkHighContrast = Color(0xFF2C322B)
val surfaceContainerHighDarkHighContrast = Color(0xFF373D36)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424841)


val sampleColor = listOf(
    Color(0xFF466D1D),
    Color(0xFF30C67C),
)

val borderStrokeColor = listOf(
    Color(0xFF7C0902),
    Color(0xFFE60026),
    Color(0xFFDA2C43)
)

val rainbowColor = listOf(
    Color.Red,
    Color.Magenta,
    Color.Yellow,
    Color.Blue
)